# This is a basic workflow to help you get started with Actions

name: CMake

on:
  push: 
    branches: [ master ]
  workflow_dispatch: 
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: prep
      run: |
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install conan
        sudo apt-get install -y gcc-10 g++10
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 --slave /usr/bin/g++ g++ /usr/bin/g++-10
        update-alternatives --install /usr/bin/cc  cc /usr/bin/gcc 30
        update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30

    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: make
        run: make
	
