# Workflow to configure with cmake and build with gcc-10

name: Build with gcc-10

on:
  push: 
    branches: [ master ]
  workflow_dispatch: 
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: prep
      run: |
        sudo pip3 install conan
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 --slave /usr/bin/g++ g++ /usr/bin/g++-10
        sudo update-alternatives --install /usr/bin/cc  cc /usr/bin/gcc 30
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30

    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: make
      run: |
        cd build
        make
